### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by Ev1lbl0w** [retrohub-org/retrohub#13]
RetroHub has no logo. It needs a logo. That's it really ¯\_(ツ)_/¯

**Comment by lynnpepin** [comment]
I love the idea for this project! My favorite games have hub worlds, and I love the idea of a hub world for emulators. I found this project because you had it tagged for Hacktoberfest! :)

What do you think of this logo? I like to think of this screen being like the portals in Gauntlet: Dark Legacy or the paintings in Super Mario 64.

![image](https://user-images.githubusercontent.com/19627675/194727172-5cd98ceb-9b27-4b93-8eb0-f401f49a0ce6.png)

If you like this as is, I'd love to make a PR to add it as the logo.

**Comment by lynnpepin** [comment]
![image](https://user-images.githubusercontent.com/19627675/194728210-78034624-e491-4dd0-bfa2-c116852bdf85.png)

*Oops, and an alternate version with easier-to-read text

**Comment by Ev1lbl0w** [comment]
Hey, thank you for your contribution!

I like the logo concept, good job! I'm still in doubt in the text though; making it darker helped making it readable, but it still feels a bit too hard to read it properly.

Regardless, go ahead and open a PR to submit this version (the most recent one, with the dark text)! RetroHub is still in "alpha" and I've yet to think of a general design for it, so there's no point in me suggesting changes to the logo right now without having yet a clear idea on how the app will look like.

For the PR, I suggest placing the files under `assets/icons/app`. Let me know if you already have a license you wish to place your icon under. If not, no worries, I'll handle licensing stuff later on and I'll suggest you one (almost certainly something under [Creative Commons](https://creativecommons.org/)). I'll then place the logo in the README.md, in the app eventually when I create an UI for it, and credit your contribution.

Once again, thank you for your work!

**Comment by lynnpepin** [comment]
Understood! I put the GIMP .xcf source file + a few alt versions under `assets/icons/app`, without touching any other files. I'm happy with whatever license you choose, so long as it's a reasonably open license. I'll make a PR now!
