### ISSUE TITLE
Input still recognized while out of focus

### ISSUE THREAD

**Issue by rsubtil** [retrohub-org/retrohub#36]
RetroHub is still picking up joystick input when the app is out of focus. This is problematic as it can change settings in the background and mess things up without the user noticing. Input should only be accepted when the app is focused (this is not an issue with keyboard/mouse as the OS manages app focus instead)

**Comment by Ev1lbl0w** [comment]
This may require changes in Godot due to UI events. There's https://github.com/godotengine/godot/issues/16832 which points to a [commit](https://github.com/Calinou/godot/commit/86f2ba354dc7a1705990ec700ae44e4f164669f7) that might be easily cherry-pickable.

For now, it might be sufficient to handle this in code and avoid opening UI elements when out-of-focus. This however might not solve all issues if there's existing UI elements. A solution will be tried, but if more issues arise of this, it's better to patch Godot altogether.

**Comment by rsubtil** [comment]
Fixed with https://github.com/retrohub-org/retrohub/commit/c7dad0463e6694cdfc4545272b1b11bd1b0fd08a
